[tool.ruff]
target-version = "py313"

select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "I",   # isort
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "SIM", # flake8-simplify
]

ignore = [
    "E402",
    "E501",
    "B905",
    "N803",
    "N806",
    "N812",
    "B008",
]

exclude = [
    ".git",
    ".ipynb_checkpoints",
    "__pycache__",
    "*.ipynb_checkpoints",
    "venv",
    ".venv",
    "env",
    "build",
    "dist",
]